### ISSUE TITLE
Sporadic crash from invalid touch event

### ISSUE THREAD

**Issue by kulakowski** [domokit/sky_engine#339]
I can very occasionally get an app to crash on a null value here: https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/lib/rendering/sky_binding.dart#L108

Unfortunately, this isn't very reliable, nor have I been able to get a value for `event.type`.

```
[0728/151759:ERROR:dart_error.cc(19)] Unhandled exception:
The null object does not have a getter 'lastPosition'.

NoSuchMethodError: method not found: 'lastPosition'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SkyBinding._handlePointerEvent (http://127.0.0.1:31842/packages/sky/rendering/sky_binding.dart:126:35)
#3      SkyBinding._handleEvent (http://127.0.0.1:31842/packages/sky/rendering/sky_binding.dart:84:7)
[0728/151759:ERROR:dart_error.cc(28)] #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SkyBinding._handlePointerEvent (http://127.0.0.1:31842/packages/sky/rendering/sky_binding.dart:126:35)
#3      SkyBinding._handleEvent (http://127.0.0.1:31842/packages/sky/rendering/sky_binding.dart:84:7)
```

**Comment by abarth** [comment]
I have a theory.  Suppose you drag your finger from one mojo::View to another.  I bet it's possible to receive an "up" event without ever getting the corresponding "down" or "move" events.

If that's true, the problem is an underlying mismatch between the event models in view_manager and Sky.  Sky assumes a mobile-like capturing model whereby all the pointer events related to a given finger are directed at whatever received the "down" for that finger.  I bet view_manager has a desktop-like model whereby events are not captured and instead continuously hit tested on every move.
