### ISSUE TITLE
the travis build takes a while to run

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_engine#805]
Builds look like they currently take 18-20 minutes:

https://travis-ci.org/domokit/sky_engine/builds

I haven't looked at where most of the time is spent, but it would be great to get the build times down to a few minutes. Some things you can do with travis:

- if your build does not require `sudo`, you can run on travis' new containerized build infrastructure. I _believe_ it'll schedule the builds onto machines with slightly more resources (cpu+memory). There is much reduced latency in your build starting up. Generally, travis promises faster builds when using their containerized infrastructure.
- you can cache some directories between builds if it's helpful (see https://github.com/dart-lang/dartdoc/blob/master/.travis.yml#L13)
- you can shard builds if that's useful. So, if building and testing two configurations, you can do that in two parallel builds instead of sequentially in the same build. It's just a matter of setting and then checking env variables (https://github.com/dart-lang/dartdoc/blob/master/.travis.yml#L6)

**Comment by abarth** [comment]
The underlying problem is that we build C++ code on Travis.  Some of the Ubuntu packages we need to build the C++ aren't available in the containerized world.  Also, the bulk of the time is spent building the C++ code.

One way to make the build cycle faster is to split the C++ and Dart code into separate repos so that people who work on the Dart code can get a fast cycle using pre-built binaries from the C++ repo.

**Comment by jamesr** [comment]
There's also a lot of runtime-dead C++ code being built right now, deleting that would also speed things up.

**Comment by devoncarew** [comment]
fixed!
