### ISSUE TITLE
Size vs Screen Resolution

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#923]
My current device's resolution is 1080 x 1920, but when I use a SizeObserver, I'm told that I have 360.0 x 592.0 (portrait) and 598.0 x 360.0 (landscape).

Questions:
* Why is it 592.0 in portrait and 598.0 in landscape? Notably, 1080 / 360 = 3, but 1920 / 3 = 640.
* How can I make Size match my Screen Resolution?

I found this out by putting a SizeObserver on my App's `Widget build()` method, rotating my phone between portrait and landscape, and checking `adb logcat`.

```
import 'package:sky/widgets.dart';
import 'dart:sky' as sky;

class MyApp extends App {
  void sizeChanged(sky.Size newSize) {
    print(newSize);
  }

  Widget build() {
    return new SizeObserver(
      callback: sizeChanged,
      child: new Container()
    );
  }
}

void main() {
  runApp(new MyApp());
}
```

**Comment by abarth** [comment]
The reason is that on Android there is a black region at the bottom of the screen that contains the back, home, and recents buttons.  In portrait mode, that black region deducts from the long axis.  In landscape, it does not.

If you like, you can use the `activity` service to enter immersive mode [1] which hides most of the Android system controls.

https://developer.android.com/training/system-ui/immersive.html

**Comment by afandria** [comment]
So to reiterate, this is working as Android intends.

For me to enter immersive mode, I need to do something like this:

```
import 'package:sky/mojo/activity.dart'; // This exports activity, which is an ActivityProxy's ptr.

activity.setSystemUiVisibility(SystemUIVisibility_IMMERSIVE);
```

**Comment by abarth** [comment]
Yep.  There's #579 open about immersive mode not being sticky enough, but what we have now should give you a sense.

**Comment by abarth** [comment]
I'm going to mark this as closed.  Please let me know if you think there's something we should do differently here.

**Comment by afandria** [comment]
Thanks for the help. That works for me.
